FROM registry.access.redhat.com/ubi9/ubi
RUN mkdir -p /tmp/websphere/agent \
&& mkdir -p /tmp/websphere/response
COPY agent.installer.linux.gtk.x86_64_1.9.2008.20240227_0018.zip /tmp/websphere/agent
COPY start.sh /root/

RUN dnf install -y unzip \
&&  cd /tmp; unzip /tmp/websphere/agent/agent.installer.linux.gtk.x86_64_1.9.2008.20240227_0018.zip \
&&  ./installc -acceptLicense
RUN /opt/IBM/InstallationManager/eclipse/tools/imcl -acceptLicense \
   install com.ibm.cic.packagingUtility \
  -repositories https://www.ibm.com/software/repositorymanager/com.ibm.cic.packagingUtility \
  -secureStorageFile /root/credential.store -masterPasswordFile /root/master_password.txt \
  -log /root/install_log$(date +%s).xml -showProgress

CMD ["/usr/bin/sh", "/root/start.sh"]

# /opt/IBM/PackagingUtility/PUCL copy com.ibm.cic.agent -repositories https://www.ibm.com/software/repositorymanager/com.ibm.cic.agent -target /var/local -secureStorageFile /root/credential.store -masterPasswordFile /root/master_password.txt -showProgress -acceptLicense


# /opt/IBM/PackagingUtility/PUCL copy com.ibm.java.jdk.v8 -repositories https://www.ibm.com/software/repositorymanager/com.ibm.java.jdk.v8 -target /var/local -secureStorageFile /root/credential.store -masterPasswordFile /root/master_password.txt -showProgress -acceptLicense
# /opt/IBM/PackagingUtility/PUCL copy com.ibm.websphere.IHS.v90 -repositories https://www.ibm.com/software/repositorymanager/com.ibm.websphere.IHS.v90 -target /var/local -secureStorageFile /root/credential.store -masterPasswordFile /root/master_password.txt -showProgress -acceptLicense
# /opt/IBM/PackagingUtility/PUCL copy com.ibm.websphere.PLG.v90 -repositories https://www.ibm.com/software/repositorymanager/com.ibm.websphere.PLG.v90 -target /var/local -secureStorageFile /root/credential.store -masterPasswordFile /root/master_password.txt -showProgress -acceptLicense
# /opt/IBM/PackagingUtility/PUCL copy com.ibm.websphere.BASE.v90 -repositories https://www.ibm.com/software/repositorymanager/com.ibm.websphere.BASE.v90 -target /var/local -secureStorageFile /root/credential.store -masterPasswordFile /root/master_password.txt -showProgress -acceptLicense
# /opt/IBM/PackagingUtility/PUCL copy com.ibm.cic.packagingUtility -repositories https://www.ibm.com/software/repositorymanager/com.ibm.cic.packagingUtility -target /var/local -secureStorageFile /root/credential.store -masterPasswordFile /root/master_password.txt -showProgress -acceptLicense

# /opt/IBM/InstallationManager/eclipse/tools/imcl listInstalledPackages
# /opt/IBM/InstallationManager/eclipse/tools/imcl listAvailablePackages -repositories https://repos.nfs.info/wasrepo/ -preferences com.ibm.cic.common.core.preferences.ssl.nonsecureMode=true
